version: '2'
services:
  app:
    image: scalac/rvm:latest
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    entrypoint: bash -l -c "rm -f tmp/pids/* && gem install bundler && bundle && rails s -b 0.0.0.0"
    depends_on:
      - db
  db:
    image: mariadb:latest
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/docker/db/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app_db
      - MYSQL_ROOT_PASSWORD=secret
